### PR TITLE
Bugfix - Empty string as default, so it can be altered. Auto-detect l…

### PR DESCRIPTION
**Pull request by luku**
Thanks a lot for handy library! 

I found few bugs and improvements:
- Empty string as default, so it can be altered (`isset()` for `null` keys is `false`)
- Auto-detect language
- Do not force IP
- Updated docs

### CODE REVIEW

**Comment by xorock** [comment]
Thank You for contribution. Could You tell me more what is the purpose of changing "Empty string as default, so it can be altered (isset() for null keys is false)"? Code is checked for empty values, isset for null but initialised variable will return true. Language is forced because it may be needed on specific use case. I've fixed getHtml() method.

**Comment by luku** [comment]
Ok, the point is that you cannot pass any `onload` parameter and `callback`, `expired-callback` attributes when initiating ReCaptcha2 via its adapter `Ghost_Captcha_ReCaptcha2`. Because on line [150](https://github.com/xorock/ZF1-Google-Recaptcha-v2/blob/master/library/Ghost/Captcha/ReCaptcha2.php#L150) and [154](https://github.com/xorock/ZF1-Google-Recaptcha-v2/blob/master/library/Ghost/Captcha/ReCaptcha2.php#L154) you're checking if the parameter/attribute key is set. It will always return false when the default value is null. This doesn't happen if you're adding ReCatpcha2 via `addElement()` method, but it's still valid use case, as you can see in [ZF docs](https://framework.zend.com/manual/1.10/en/zend.service.recaptcha.html), if you don't use ReCaptcha2 inside `Zend_Form`. Alternative solution would be to use condition `array_key_exists()` instead of `isset()`, if you prefer to keep the defaults as `null`.

As for language, I don't think it's good idea to force it by default. Because then it's impossible (with the current implementation) to omit it, if you really want ReCaptcha2 to detect user's language.

**Comment by xorock** [comment]
You can pass any options and attributes to the constructor of `Ghost_Captcha_ReCaptcha2` and it will proxy to valid service methods.
I don't remember now but I think, when wrote this code, language was required.

**Comment by luku** [comment]
> You can pass any options and attributes to the constructor of  Ghost_Captcha_ReCaptcha2  and it will proxy to valid service methods.

No, it won't. Here is example with passing `onload` callback.
```php
$captcha = new Ghost_Captcha_ReCaptcha2(array(
    'pubkey' => 'public key',
    'privkey' => 'secret key',
    'onload' => 'myOnloadCallback'
));
echo $captcha->getService()->getHtmlHead();
```
**Expected:**
```html
<script src="https://www.google.com/recaptcha/api.js?render=onload&onload=myOnloadCallback" defer async></script>
```
**Actual:**
```html
<script src="https://www.google.com/recaptcha/api.js?render=onload" defer async></script>
```

**Comment by xorock** [comment]
You're right. Fixed.

**Pull request closed without merging**
